### ISSUE TITLE
execjs._exceptions.ProgramError: ReferenceError: "exports" is not defined

### ISSUE THREAD

**Issue by appleyuchi** [zkqiang/Zhihu-Login#13]
`Traceback (most recent call last):
  File "zhihu_login.py", line 203, in <module>
    account.login(captcha_lang='en', load_cookies=True)
  File "zhihu_login.py", line 84, in login
    data = self._encrypt(self.login_data)
  File "zhihu_login.py", line 198, in _encrypt
    return js.call('Q', urlencode(form_data))
  File "/home/appleyuchi/.virtualenvs/python3.6/lib/python3.6/site-packages/execjs/_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "/home/appleyuchi/.virtualenvs/python3.6/lib/python3.6/site-packages/execjs/_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "/home/appleyuchi/.virtualenvs/python3.6/lib/python3.6/site-packages/execjs/_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "/home/appleyuchi/.virtualenvs/python3.6/lib/python3.6/site-packages/execjs/_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "/home/appleyuchi/.virtualenvs/python3.6/lib/python3.6/site-packages/execjs/_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "/home/appleyuchi/.virtualenvs/python3.6/lib/python3.6/site-packages/execjs/_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: ReferenceError: "exports" is not defined`
无法运行，求解决，谢谢

**Comment by zkqiang** [comment]
安装nodejs，版本不低于6.0
