### ISSUE TITLE
报错：execjs._exceptions.ProgramError: TypeError: 'exports' 未定义

### ISSUE THREAD

**Issue by midpushgogo** [zkqiang/Zhihu-Login#8]
验证码输入完之后报错：
Traceback (most recent call last):
  File "C:\Users\WangZeHao\Desktop\zhihu\Zhihu-Login\zhihu_login.py", line 203, in <module>
    account.login(captcha_lang='en', load_cookies=True)
  File "C:\Users\WangZeHao\Desktop\zhihu\Zhihu-Login\zhihu_login.py", line 84, in login
    data = self._encrypt(self.login_data)
  File "C:\Users\WangZeHao\Desktop\zhihu\Zhihu-Login\zhihu_login.py", line 198, in _encrypt
    return js.call('Q', urlencode(form_data))
  File "C:\Users\WangZeHao\AppData\Local\Programs\Python\Python37\lib\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "C:\Users\WangZeHao\AppData\Local\Programs\Python\Python37\lib\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "C:\Users\WangZeHao\AppData\Local\Programs\Python\Python37\lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "C:\Users\WangZeHao\AppData\Local\Programs\Python\Python37\lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "C:\Users\WangZeHao\AppData\Local\Programs\Python\Python37\lib\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "C:\Users\WangZeHao\AppData\Local\Programs\Python\Python37\lib\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: TypeError: 'exports' 未定义

请问这怎么办

**Comment by zkqiang** [comment]
应该是 js 环境没有配好，具体请搜索 pyexecjs 相关问题吧
